# name: Terraform

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   terraform-plan:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v3
      
#     - name: Terraform Init
#       run: terraform init
      
#     - name: Terraform Plan
#       run: terraform plan

#   terraform-apply:
#     runs-on: ubuntu-latest
#     needs: terraform-plan
#     if: github.ref == 'refs/heads/main'
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v3
      
#     - name: Terraform Init
#       run: terraform init
      
#     - name: Terraform Apply
#       run: terraform apply -auto-approve